# Generated by Django 5.2.5 on 2025-08-09 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分组名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分组描述')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='是否为虚拟分组')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_check_status',
            field=models.JSONField(blank=True, null=True, verbose_name='上次巡检结果'),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Mac地址'),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='终端型号'),
        ),
        migrations.AddField(
            model_name='device',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='操作系统版本'),
        ),
        migrations.AddField(
            model_name='device',
            name='software_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='软件版本'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(default='offline', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='终端唯一标识'),
        ),
        migrations.AlterField(
            model_name='device',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='推送令牌'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_heartbeat',
            field=models.DateTimeField(auto_now=True, verbose_name='最后心跳时间'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备名称'),
        ),
        migrations.AddField(
            model_name='device',
            name='groups',
            field=models.ManyToManyField(blank=True, to='devices.group', verbose_name='所属分组'),
        ),
    ]
