# Generated by Django 5.0.7 on 2025-08-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_status_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
    ]
